import { useEffect, useMemo, useState } from "react";
import { fetchRunTextFile } from "../../api/client";
import { parseFreeSurferStats, type FreeSurferStatsTable } from "../../lib/freesurferStats";

export default function FreeSurferStatsViewer({ runId, path, onClose }: { runId: number; path: string; onClose: () => void }) {
  const [table, setTable] = useState<FreeSurferStatsTable | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  useEffect(() => {
    let active = true;
    fetchRunTextFile(runId, path).then((text) => { if (active) setTable(parseFreeSurferStats(text)); }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "Statistics preview failed."); });
    return () => { active = false; };
  }, [path, runId]);
  const rows = useMemo(() => table?.rows.filter((row) => row.name.toLowerCase().includes(query.trim().toLowerCase())) ?? [], [query, table]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80"><div className="mx-4 flex h-[85vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl border border-white/10 bg-slate-950"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><h3 className="text-sm font-semibold text-white">FreeSurfer segmentation statistics</h3><p className="font-mono text-[10px] text-slate-500">{path}</p></div><button type="button" onClick={onClose} className="rounded px-2 py-1 text-xs text-slate-300 hover:bg-white/5">Close</button></header>{error ? <div className="p-6 text-sm text-red-300">{error}</div> : !table ? <div className="p-6 text-sm text-slate-400">Loading statistics…</div> : <div className="min-h-0 flex-1 overflow-auto p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><input aria-label="Search segmentation statistics" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search regions…" className="rounded border border-white/10 bg-slate-900 px-3 py-2 text-xs text-white" /><span className="text-[10px] text-slate-500">{rows.length} regions · source units preserved</span></div>{table.measures.length > 0 && <div className="mb-3 grid gap-2 sm:grid-cols-3">{table.measures.slice(0, 6).map((measure) => <div key={measure.name} className="rounded border border-white/8 bg-white/[0.03] p-2"><div className="truncate text-[9px] uppercase tracking-wide text-slate-500">{measure.name}</div><div className="mt-0.5 font-mono text-xs text-slate-200">{measure.value.toLocaleString()} {measure.units}</div></div>)}</div>}<table className="w-full border-collapse text-left text-xs"><thead className="sticky top-0 bg-slate-900 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="px-2 py-2">ID</th><th className="px-2 py-2">Region</th><th className="px-2 py-2 text-right">Voxels</th><th className="px-2 py-2 text-right">Volume (mm³)</th><th className="px-2 py-2 text-right">Area (mm²)</th><th className="px-2 py-2 text-right">Mean thickness (mm)</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.segmentationId}-${row.name}-${index}`} className="border-t border-white/5 text-slate-300"><td className="px-2 py-2 font-mono">{row.segmentationId ?? "—"}</td><td className="px-2 py-2">{row.name}</td><td className="px-2 py-2 text-right font-mono">{row.voxelCount?.toLocaleString() ?? "—"}</td><td className="px-2 py-2 text-right font-mono">{row.volumeMm3?.toLocaleString() ?? "—"}</td><td className="px-2 py-2 text-right font-mono">{row.areaMm2?.toLocaleString() ?? "—"}</td><td className="px-2 py-2 text-right font-mono">{row.meanThicknessMm?.toFixed(3) ?? "—"}</td></tr>)}</tbody></table></div>}</div></div>;
}
